cargo-features = ["per-package-target"]

[package]
name = "contracts"
version = "0.1.0"
edition = "2021"
default-target = "riscv64imac-unknown-none-elf"

[dependencies]
types = {version = "*", path = "../types"}
ckb-std = "0.10.0"
